# -*- coding: utf-8 -*-
"""trata_log_pcibex_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtX7geiUE0v9WZwt9X_JpPJ7_Zy6ae1v
"""

# Importando bibliotecas necessárias
import pandas as pd



# Nome do arquivo CSV (substitua pelo nome do arquivo importado)
file_name = "results_dev.csv"  # Coloque o nome correto do arquivo

# Lendo o arquivo CSV ignorando linhas que começam com '#'
df = pd.read_csv(file_name, comment='#', header=None)

# Desativar a notação científica para todas as colunas
pd.options.display.float_format = '{:,.6f}'.format

# Nome do arquivo Excel existente onde os dados serão salvos como uma nova aba
excel_file_name = "Res_Pre.xlsx"

# Identificando o nome das colunas (a primeira linha do arquivo CSV agora é tratada como um registro)
colunas = [f"Coluna_{i+1}" for i in range(df.shape[1])]
df.columns = colunas

# Agrupar o DataFrame pelo identificador da primeira coluna
grupo_identificador = colunas[0]
grupos = df.groupby(grupo_identificador)

try:
    with pd.ExcelWriter(excel_file_name, engine='openpyxl', mode='a') as writer:
        for nome_grupo, grupo_df in grupos:
            # Escrever cada grupo em uma aba nomeada com o identificador do grupo
            grupo_df.to_excel(writer, sheet_name=str(nome_grupo), index=False)
except FileNotFoundError:
    with pd.ExcelWriter(excel_file_name, engine='openpyxl') as writer:
        for nome_grupo, grupo_df in grupos:
            grupo_df.to_excel(writer, sheet_name=str(nome_grupo), index=False)
